Web/Models/ErrorViewModel.cs
namespace Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Web/Controllers/BatteryInstallationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Entities.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Web.Controllers
{
    [Route("akulu-montaj")]
    public class BatteryInstallationController : Controller
    {
        private readonly ILogger<BatteryInstallationController> _logger;
        private readonly IVardiyaService _vardiyaService;

        public BatteryInstallationController(ILogger<BatteryInstallationController> logger, IVardiyaService vardiyaService)
        {
            _logger = logger;
            _vardiyaService = vardiyaService;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("vardiya")]
        public IActionResult vardiya()
        {
            return View();
        }

        [HttpPost]
        public IActionResult add(List<VardiyaDetailListSectionByDep> vard, int shiftidvardiya)
        {
            Vardiya v = new Vardiya();
            for (int i = 0; i < vard.Count(); i++)
            {
                if (vard[i].check)
                {
                    v.ShiftCode = shiftidvardiya;
                    v.SicilNo = Convert.ToInt16(vard[i].SicilNo);
                    v.CreateDate = DateTime.Now.ToShortDateString();
                    v.WeeOfYear = (DateTime.Now.DayOfYear + 1) / 7;

                    _vardiyaService.Add(v);
                }
            }
            return RedirectToAction("vardiya", "batteryinstallation");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Web/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Web.Controllers
{
    [Route("bolumler")]
    public class SectionController : Controller
    {
        private readonly ILogger<SectionController> _logger;

        public SectionController(ILogger<SectionController> logger)
        {
            _logger = logger;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    ViewData["Title"] = "Dashboard";
}

<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>IK</h3>

                <p>İnsan Kaynakları</p>
            </div>
            <div class="icon">
                <i class="nav-icon fa-solid fa-users"></i>
            </div>
            <a asp-controller="humanresource" asp-action="index" class="small-box-footer">Daha fazla bilgi.. <i
                    class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>Bölümler </h3>

                <p>Bölümler</p>
            </div>
            <div class="icon">
                <i class="nav-icon fa-solid fa-users-gear"></i>
            </div>
            <a asp-controller="section" asp-action="index" class="small-box-footer">Daha fazla bilgi.. <i
                    class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->
<!-- /.row (main row) -->

Web/Views/HumanResource/index.cshtml
@await Component.InvokeAsync("HumanResourceNav")
@await Component.InvokeAsync("HumanResourceBody")

Web/Views/Section/index.cshtml
@await Component.InvokeAsync("Section")

Web/Views/Shared/Components/BatteryInstallationBody/Default.cshtml
@model List<Entities.DTO.PersonelDetailSectionByDep>
<div class="card">
    <div class="card-header">
        <h3 style="font-weight: bold;" class="card-title float-left">Akülü Montaj Bölümü Personel Listesi </h3>
        <a asp-controller="batteryinstallation" asp-action="vardiya" class="btn btn-success float-right"><i
                class="fa-regular fa-file-lines"></i> Vardiya Oluştur</a>

        <a asp-controller="section" asp-action="battery_installation_shift_plus"
            class="btn btn-warning float-right mr-2"><i class="fa-regular fa-file-lines"></i> Fazla Mesai Oluştur</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="section-table" class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th style="max-width: 30px;">#</th>
                    <th>Personel Ad Soyad</th>
                    <th>Departman</th>
                    <th>Vardiya</th>
                    <th>İmza</th>
                </tr>
            </thead>
            <tbody>

                @{
                    int count = 1;
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="max-width: 30px;">@count</td>
                            <td>@item.Ad @item.Soyad</td>
                            <td>@item.Departman</td>
                            <td>@item.Vardiya</td>
                            <td></td>
                        </tr>
                        count++;
                    }
                }

            </tbody>
            <tfoot>
                <tr>
                    <th style="max-width: 30px;">#</th>
                    <th>Personel Ad Soyad</th>
                    <th>Departman</th>
                    <th>Vardiya</th>
                    <th>İmza</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>

Web/Views/Shared/Components/BatteryInstallationNav/Default.cshtml
<div class="row">
    <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">CPU Traffic</span>
                <span class="info-box-number">
                    10
                    <small>%</small>
                </span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
            <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-thumbs-up"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Likes</span>
                <span class="info-box-number">41,410</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix hidden-md-up"></div>

    <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
            <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Sales</span>
                <span class="info-box-number">760</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
            <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">New Members</span>
                <span class="info-box-number">2,000</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>

Web/Views/Shared/Components/BatteryInstallationVardiyaBody/Default.cshtml
<div class="card-deck">
    @* Vardiya Left *@
    @await Component.InvokeAsync("BatteryInstallationVardiyaLeftTable")
    @* Vardiya Right *@
    @await Component.InvokeAsync("BatteryInstallationVardiyaRightTable")
</div>

Web/Views/Shared/Components/BatteryInstallationVardiyaLeftTable/Default.cshtml
@* Vardiya Left *@
@model List<Entities.DTO.VardiyaDetailListSectionByDep>
<div class="card">
    <div class="card-header bg-danger">
        <div class="card-text">.Hafta Vardiya Atanmamış Personel Listesi</div>
    </div>
    <div class="card-body">
        <form asp-controller="BatteryInstallation" asp-action="add" method="post">

            <div id="radio-buttons-vardiya" class="btn-group btn-group-toggle col mb-2" data-toggle="buttons">

                <label class="btn btn-dark active col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option0" value="0" autocomplete="off" disabled>
                    Vardiya
                    <i class="fa-solid fa-angles-right"></i>
                </label>

                <label class="btn btn-outline-primary active col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option1" value="1" autocomplete="off" checked>
                    08:00
                    -
                    16:00
                </label>

                <label class="btn btn-outline-primary col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option2" value="2" autocomplete="off"> 16:00 -
                    24:00
                </label>

                <label class="btn btn-outline-primary col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option3" value="3" autocomplete="off"> 00:00 -
                    08:00
                </label>

                <label class="btn btn-outline-success col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option4" value="4" autocomplete="off"> 08:00 -
                    18:00
                </label>
                <label class="btn btn-outline-danger col-2 float-left btn-sm">
                    <input type="radio" name="options" id="option5" value="5" autocomplete="off"> 08:00 -
                    24:00
                </label>
            </div>

            <table id="section-table-vardiya" class="table table-sm table-bordered table-hover">
                <thead>
                    <tr>
                        <th style="max-width: 35px;"><i class="fa-solid fa-check"></i></th>
                        <th hidden>.</th>
                        <th hidden>.</th>
                        <th hidden>.</th>
                        <th>Personel Ad Soyad</th>
                    </tr>

                </thead>
                <tbody>

                    <input hidden type="text" name="shiftidvardiya" id="shiftidvardiya" value="1">

                    @for (int i = 0; i < Model.Count(); i++)
                    {
                        <tr>
                            <td style="max-width: 25px;">@Html.CheckBoxFor(c=>Model[i].check)</td>
                            <td hidden>@Html.TextBoxFor(m=> Model[i].SicilNo)</td>
                            <td hidden>@Html.TextBoxFor(m=> Model[i].Ad)</td>
                            <td hidden>@Html.TextBoxFor(m=> Model[i].Soyad)</td>
                            <td>@Model[i].Ad @Model[i].Soyad</td>
                        </tr>
                    }



                </tbody>
                <tfoot>
                    <tr>
                        <th style="max-width: 35px;"><i class="fa-solid fa-check"></i></th>
                        <th hidden>.</th>
                        <th hidden>.</th>
                        <th hidden>.</th>
                        <th>Personel Ad Soyad</th>
                    </tr>
                </tfoot>
            </table>
            <button type="submit" class="btn btn-sm btn-success float-right mt-2">Vardiya Kaydet</button>
        </form>
    </div>
</div>

Web/Views/Shared/Components/BatteryInstallationVardiyaRightTable/Default.cshtml
@model List<Entities.DTO.VardiyaDetailListSectionByDep>
<div class="card">
    <div class="card-header bg-success">
        <div class="card-text"> .Hafta Vardiya Listesi</div>
    </div>
    <div class="card-body">
        <div id="radio-buttons-vardiya" class="btn-group btn-group-toggle col mb-2" data-toggle="buttons">
            <label class="btn btn-dark active col-2 float-left btn-sm">
                <input type="radio" name="options" id="option0" value="0" autocomplete="off" disabled>
                Vardiya
                <i class="fa-solid fa-angles-right"></i>
            </label>

            <label class="btn btn-outline-primary active col-2 float-left btn-sm">
                <input type="radio" name="options" id="option1" value="1" autocomplete="on" checked> 08:00
                -
                16:00
            </label>

            <label class="btn btn-outline-primary col-2 float-left btn-sm">
                <input type="radio" name="options" id="option2" value="2" autocomplete="on"> 16:00 - 24:00
            </label>

            <label class="btn btn-outline-primary col-2 float-left btn-sm">
                <input type="radio" name="options" id="option3" value="3" autocomplete="on"> 00:00 - 08:00
            </label>

            <label class="btn btn-outline-success col-2 float-left btn-sm">
                <input type="radio" name="options" id="option4" value="4" autocomplete="on"> 08:00 - 18:00
            </label>
            <label class="btn btn-outline-danger col-2 float-left btn-sm">
                <input type="radio" name="options" id="option5" value="5" autocomplete="on"> 08:00 - 24:00
            </label>
        </div>

        <table id="example1-shift1-result" class="table table-sm table-bordered table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Personel Ad Soyad</th>
                    <th>Vardiya</th>

                </tr>
            </thead>
            <tbody>

            </tbody>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Personel Ad Soyad</th>
                    <th>Vardiya</th>
                </tr>
            </tfoot>
        </table>
        <button id="vardiya-delete" type="submit" class="btn btn-sm btn-danger float-right mt-2">Vardiya
            Sil</button>
    </div>
</div>

Web/Views/Shared/Components/HumanResourceBody/Default.cshtml
@model List<Entities.DTO.PersonelDetailHR>
<div class="card">
    <div class="card-header">
        <h3 style="font-weight: bold;" class="card-title float-left">Personel Listesi </h3>
        <a href="#" class="btn btn-success float-right"><i class="fa-regular fa-file-lines"></i> Fazla Mesai Listesi</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="ik-table" class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>TC Kimlik</th>
                    <th>Sicil No</th>
                    <th>Personel Ad Soyad</th>
                    <th>Departman</th>
                    <th>Bölge</th>
                    <th>Durak</th>
                    <th>Vardiya</th>
                </tr>
            </thead>
            <tbody>

                @* @{
                    int count = 1;
                    @foreach (var item in Model)
                    {
                    <tr>
                    <td>@count</td>
                    <td>@item.TCKN</td>
                    <td>@item.SicilNo</td>
                    <td>@item.DepartmanName</td>
                    <td>@item.Name @item.Surname</td>
                    <td>@item.ServiceName</td>
                    <td>@item.StationName</td>
                    <td>@item.ShiftName</td>
                    </tr>
                    count++;
                    }
                    } *@

                @foreach (var item in Model)
                {
                    <tr>
                        <td>#</td>
                        <td>@item.TCKN</td>
                        <td>@item.SicilNo</td>
                        <td>@item.Ad @item.Soyad</td>
                        <td>@item.Departman</td>
                        <td>@item.Servis</td>
                        <td>@item.Durak</td>
                        <td>@item.Vardiya</td>
                    </tr>
                }

            </tbody>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>TC Kimlik</th>
                    <th>Sicil No</th>
                    <th>Departman</th>
                    <th>Personel Ad Soyad</th>
                    <th>Bölge</th>
                    <th>Durak</th>
                    <th>Vardiya</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>

Web/Views/Shared/Components/Section/Default.cshtml
<div class="row">
    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="batteryinstallation" asp-action="index" class="text-dark">
            <div class="info-box">
                <span class="info-box-icon bg-info elevation-1"><i class="fa-solid fa-car-battery"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Akülü Montaj</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="injection" class="text-dark">
            <div class="info-box mb-3">
                <span class="info-box-icon bg-danger elevation-1"><i class="fa-solid fa-fill-drip"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Enjeksiyon</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix hidden-md-up"></div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="molding_room" class="text-dark">
            <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fa-solid fa-layer-group"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Kalıphane</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="toy_assembly" class="text-dark">
            <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fa-solid fa-puzzle-piece"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Oyuncak Montaj</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->
</div>

<div class="row">
    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="puffing" class="text-dark">
            <div class="info-box">
                <span class="info-box-icon bg-primary elevation-1"><i class="fa-solid fa-cloud-arrow-up"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Şişirme</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="warehouse" class="text-dark">
            <div class="info-box mb-3">
                <span class="info-box-icon bg-dark elevation-1"><i class="fa-solid fa-warehouse"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Sevkiyat Depo</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- /.col -->

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="furniture" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #C3614C;" class="info-box-icon elevation-1 text-white"><i
                        class="fa-solid fa-couch"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Mobilya</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="maintenance" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #333399;" class="info-box-icon elevation-1 text-white"><i
                        class="fa-solid fa-screwdriver-wrench"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Bakım Onarım</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="accept_goods" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #ff9900;" class="info-box-icon elevation-1 text-white"><i
                        class="fa-solid fa-box-open"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Mal Kabul</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="press_shop" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #669999;" class="info-box-icon elevation-1 text-white">
                    <i class="fa-solid fa-gauge-simple-high"></i>
                </span>

                <div class="info-box-content">
                    <span class="info-box-text">Preshane</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="rotation" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #9933ff;" class="info-box-icon elevation-1 text-white">
                    <i class="fa-solid fa-location-crosshairs"></i>
                </span>

                <div class="info-box-content">
                    <span class="info-box-text">Rotasyon</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>

    <div class="col-12 col-sm-6 col-md-3">
        <a asp-controller="section" asp-action="planning" class="text-dark">
            <div class="info-box mb-3">
                <span style="background-color: #cccc00;" class="info-box-icon elevation-1 text-white">
                    <i class="fa-solid fa-play"></i>
                </span>

                <div class="info-box-content">
                    <span class="info-box-text">Planlama</span>
                    <span class="info-box-number">1</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </a>

    </div>
    <!-- fix for small devices only -->

    <!-- /.col -->
</div>